### ISSUE TITLE
Huggingface conversion after pretrain / finetune 

### ISSUE THREAD

**Issue by StephennFernandes** [bertin-project/bertin-t5x#3]
@versae Did you try porting the t5x models to Huggingface once pretrained and/or finetuned ? 
I was able to convert the model to HF, but what about the tokenizer ? how to convert the tokenizer to HF

**Comment by versae** [comment]
That depends on the tokenizer type used. Haven't got around that yet, so an help would be welcome 😀

**Comment by StephennFernandes** [comment]
i hope this helps. https://discuss.huggingface.co/t/how-to-convert-the-new-t5x-models-to-huggingface-transformers/19175
