### ISSUE TITLE
how do i too add the extra_ids already for the tokenizer such that i could keep the extra_ids=0

### ISSUE THREAD

**Issue by StephennFernandes** [bertin-project/bertin-t5x#5]
@versae I've been seeing in the mt5 tokenizer the extra 100 ids needed for the sentinel tokens come already included in the tokenizer. 
`'gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model'` 

how do i too train my own sentencepiece tokenizer where i could too include the 100extra already in my tokenizer, just like the original one above.

as i am training a variant of mt5 that covers multiple langugaes that the common mt5 does cover. i went on to training a unigram sentencpiece tokenizer with 250000 vocab_size but i tripped into confusion, on how to get the 100 extra_ids similar the the official mt5 tokenizer.

**Comment by versae** [comment]
I'm not sure how to add the extra tokens using SentencePiece, but SeqIO supports both models with the extra ids and models without them. If your model includes extra tokens, you just create a vocabulary:

```python
vocabulary = seqio.SentencePieceVocabulary("gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model")
```

If your model **does not** include extra ids and you want them in your vocabulary, you can still instruct SeqIO to add them on the fly:


```python
vocabulary = seqio.SentencePieceVocabulary("gs://bertin-project/t5/vocabs/wikipedia/es_32000_unigram.sp.model", extra_ids=100)
```

**Comment by StephennFernandes** [comment]
found something here: https://github.com/google-research/multilingual-t5/issues/24#issuecomment-1234416611
